# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4737df3928583b0114a188c9f5fa5bcc73647baf0f0f3f32bdcf6adebeb270a25a281f5cd6e5ed2e536a0e988e1984ff464ac6023b209cffc9d582db5ca474a

test:
  secret_key_base: 30690db726dbcd7a3d9b693dcf019345702286e2b6eb181e9f27ba0c5efd58aaf27dcabc5ef350f67c86b4c264eb87642f7ada1df8a1a2c9ab4b91bcd842dd0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
